apiVersion: apps/v1
kind: Deployment
metadata:
  name: pal-tracker
  labels:
    app: pal-tracker
    foo: bar4
spec:
  selector:
    matchLabels:
      app: pal-tracker
      name: pal-tracker-pod
  template:
    metadata:
      labels:
        app: pal-tracker
        name: pal-tracker-pod
    spec:
      containers:
        - name: pal-tracker-container
          image: ellinj/pal-tracker:build-18
          envFrom:
          - secretRef:
              name: db-credentials
          env:
          - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
            value: "*"
          - name: MANAGEMENT_ENDPOINT_HEALTH_SHOWDETAILS
            value: always
          - name: WELCOME_MESSAGE
            valueFrom:
              configMapKeyRef:
                    name: pal-tracker
                    key: welcome.message
          - name: SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE
            valueFrom:
              configMapKeyRef:
                name: pal-tracker
                key: spring.datasource.hikari.maximumpoolsize
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 150
